
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


homeassistant:
  legacy_templates: false
  name: Rumah Kita
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: !env_var HASS_ELEVATION
  unit_system: metric
  time_zone: Asia/Makassar
  country: ID
  packages: !include packages/package.yaml

utility_meter:
  daily_energy:
    name: Daily Energy
    source: sensor.em_main_energy_today
    cycle: daily

input_number:
  energy_tariff:
    name: Energy Tariff
    initial: 1444.7
    mode: box
    min: 1000
    max: 10000
    step: 0.1
    unit_of_measurement: IDR/kWh