
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


homeassistant:
  legacy_templates: false
  name: Rumah Kita
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: !env_var HASS_ELEVATION
  unit_system: metric
  time_zone: Asia/Makassar
  country: ID

