#homeassistant: !include hass/package.yaml
homeassistant_integrations: !include_dir_merge_named integrations/

master_bedroom: !include ./zones/master-bedroom/package.yaml
living_room: !include ./zones/living-room/package.yaml